apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: customer